// ── Seed Script ────────────────────────────────────────────
// Run with: npm run seed
// This moves all 60+ questions from the frontend JS file into MongoDB
// Also creates the admin user
// ──────────────────────────────────────────────────────────

const mongoose = require("mongoose");
const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");

dotenv.config();

const Question = require("../models/Question");
const User = require("../models/User");

// ── All 60+ questions copied from frontend/src/data/questions.js ──
const QUESTIONS = [
  // ── FRONTEND ──────────────────────────────────────────────
  { title: "What is the Virtual DOM and how does React use it?", description: "Explain the concept of the Virtual DOM, why it was introduced, and how React uses it to efficiently update the real DOM.", role: "Frontend", topic: "React", difficulty: "Easy", modelAnswer: "The Virtual DOM is a lightweight, in-memory representation of the actual DOM tree. React maintains a virtual DOM and when state or props change, it creates a new virtual DOM tree. React then diffs the new tree against the previous one using its reconciliation algorithm, computing the minimum set of changes needed. Only those changes are applied to the real DOM in a batch, which is far more efficient than direct DOM manipulation. This process is called reconciliation.", explanation: "React introduced the Virtual DOM to solve the performance bottleneck of frequent real DOM updates.", keywords: ["Virtual DOM", "reconciliation", "diffing algorithm", "real DOM", "batch update", "performance"] },
  { title: "Explain the difference between controlled and uncontrolled components.", description: "What are controlled and uncontrolled components in React? When would you use each approach?", role: "Frontend", topic: "React", difficulty: "Easy", modelAnswer: "A controlled component is one where React controls the form data via state. The input's value is tied to a state variable, and onChange updates the state. An uncontrolled component uses the DOM itself to store form data, accessed via refs.", explanation: "The key distinction is where the source of truth lives — in React state (controlled) or the DOM (uncontrolled).", keywords: ["controlled", "uncontrolled", "state", "ref", "onChange", "value", "form"] },
  { title: "What are React Hooks? Explain useState and useEffect.", description: "Describe React Hooks and provide detailed explanations of the useState and useEffect hooks.", role: "Frontend", topic: "React", difficulty: "Easy", modelAnswer: "Hooks are functions that let you use React state and lifecycle features in functional components. useState returns a state variable and a setter function. useEffect runs side effects after render; it accepts a callback and a dependency array.", explanation: "Hooks were introduced in React 16.8 to enable stateful logic in functional components.", keywords: ["hooks", "useState", "useEffect", "dependency array", "side effects", "functional components"] },
  { title: "Explain CSS specificity and how it works.", description: "How does CSS specificity determine which styles are applied when multiple rules match the same element?", role: "Frontend", topic: "CSS", difficulty: "Easy", modelAnswer: "CSS specificity is a weight that determines which CSS rule takes precedence. It's calculated as a 4-part value: inline styles (1,0,0,0), IDs (0,1,0,0), classes/attributes/pseudo-classes (0,0,1,0), elements/pseudo-elements (0,0,0,1).", explanation: "Understanding specificity prevents unexpected style overrides.", keywords: ["specificity", "inline styles", "ID", "class", "element", "cascade", "!important"] },
  { title: "What is the difference between flexbox and CSS Grid?", description: "Compare flexbox and CSS Grid layout systems. When would you choose one over the other?", role: "Frontend", topic: "CSS", difficulty: "Easy", modelAnswer: "Flexbox is a one-dimensional layout system handling layout in either a row or column direction. Grid is two-dimensional handling rows and columns simultaneously.", explanation: "Neither is strictly superior; they solve different problems.", keywords: ["flexbox", "grid", "one-dimensional", "two-dimensional", "row", "column", "layout"] },
  { title: "What is event bubbling and event delegation in JavaScript?", description: "Explain event bubbling in the DOM and how event delegation takes advantage of it.", role: "Frontend", topic: "JavaScript", difficulty: "Medium", modelAnswer: "Event bubbling is the process where an event triggered on a child element propagates up through its ancestors. Event delegation leverages this by placing a single event listener on a parent element instead of multiple listeners on each child.", explanation: "Event delegation is a key performance optimization for lists with many items.", keywords: ["event bubbling", "event delegation", "propagation", "event.target", "stopPropagation"] },
  { title: "Explain the concept of closures in JavaScript.", description: "What is a closure? Provide an example and explain common use cases.", role: "Frontend", topic: "JavaScript", difficulty: "Medium", modelAnswer: "A closure is a function that retains access to its outer scope's variables even after the outer function has returned.", explanation: "Closures are fundamental to JavaScript and power many patterns.", keywords: ["closure", "lexical scope", "outer function", "inner function", "data privacy"] },
  { title: "What is the difference between localStorage, sessionStorage, and cookies?", description: "Compare these three browser storage mechanisms.", role: "Frontend", topic: "Web APIs", difficulty: "Medium", modelAnswer: "localStorage persists indefinitely with ~5-10MB capacity. sessionStorage persists only for the browser tab session. Cookies persist based on an expiry date with ~4KB capacity, sent with every HTTP request.", explanation: "Choosing the wrong storage mechanism can cause security vulnerabilities or data loss.", keywords: ["localStorage", "sessionStorage", "cookies", "persistence", "capacity", "httpOnly"] },
  { title: "How does React's useContext hook work and when should you use it?", description: "Explain React Context, the useContext hook, and appropriate vs inappropriate use cases.", role: "Frontend", topic: "React", difficulty: "Medium", modelAnswer: "React Context provides a way to pass data through the component tree without prop drilling. You create a context with createContext(), wrap with Context.Provider, and consume with useContext().", explanation: "Context solves prop drilling but isn't a full state management solution.", keywords: ["useContext", "Context", "createContext", "Provider", "prop drilling", "global state"] },
  { title: "What are Web Accessibility (a11y) best practices?", description: "Describe key web accessibility guidelines and practical techniques.", role: "Frontend", topic: "Accessibility", difficulty: "Hard", modelAnswer: "Key accessibility practices include: semantic HTML, ARIA attributes for dynamic content, keyboard navigation support, sufficient color contrast (4.5:1 for normal text), alternative text for images, focus management in SPAs.", explanation: "Accessibility is a legal requirement in many jurisdictions and improves usability for everyone.", keywords: ["accessibility", "ARIA", "semantic HTML", "keyboard navigation", "screen reader", "WCAG"] },
  { title: "Explain React's reconciliation algorithm.", description: "How does React decide which parts of the DOM to update?", role: "Frontend", topic: "React", difficulty: "Hard", modelAnswer: "React's reconciliation uses two key heuristics: Elements of different types produce different trees. The key prop lets React identify which items in a list have changed, been added, or removed.", explanation: "Understanding reconciliation explains why keys matter in lists.", keywords: ["reconciliation", "diffing", "keys", "element type", "Fiber", "incremental"] },
  { title: "What is code splitting and lazy loading in React?", description: "Explain code splitting, lazy loading, and how to implement them in a React application.", role: "Frontend", topic: "Performance", difficulty: "Hard", modelAnswer: "Code splitting divides your JavaScript bundle into smaller chunks loaded on demand. React.lazy() enables component-level code splitting paired with Suspense to show a fallback while loading.", explanation: "Large bundles increase Time to Interactive. Code splitting is one of the most impactful performance optimizations.", keywords: ["code splitting", "lazy loading", "React.lazy", "Suspense", "dynamic import", "bundle"] },

  // ── BACKEND ───────────────────────────────────────────────
  { title: "What is REST and what are its key principles?", description: "Explain REST architecture, its six guiding constraints, and how they apply to API design.", role: "Backend", topic: "APIs", difficulty: "Easy", modelAnswer: "REST is an architectural style with six constraints: Client-Server separation, Statelessness, Cacheability, Uniform Interface, Layered System, and Code on Demand. RESTful APIs use HTTP methods semantically: GET (read), POST (create), PUT/PATCH (update), DELETE (delete).", explanation: "REST is the dominant API style because it leverages existing HTTP infrastructure.", keywords: ["REST", "stateless", "client-server", "HTTP methods", "GET", "POST", "PUT", "DELETE"] },
  { title: "Explain database indexing and when to use it.", description: "What are database indexes, how do they work internally, and what are the trade-offs?", role: "Backend", topic: "Databases", difficulty: "Medium", modelAnswer: "A database index is a data structure (typically a B-tree) that allows the database to find rows without scanning the entire table. They speed up SELECT queries but add overhead to INSERT, UPDATE, and DELETE operations.", explanation: "Indexes are the most impactful query optimization.", keywords: ["index", "B-tree", "query optimization", "cardinality", "SELECT", "INSERT", "overhead"] },
  { title: "What is the difference between SQL and NoSQL databases?", description: "Compare relational and non-relational databases. When would you choose each?", role: "Backend", topic: "Databases", difficulty: "Easy", modelAnswer: "SQL databases are relational, storing data in structured tables with predefined schemas, enforcing ACID properties. NoSQL databases use flexible schemas and are optimized for scale, speed, and unstructured data.", explanation: "The choice depends on data structure, query patterns, consistency requirements, and scale.", keywords: ["SQL", "NoSQL", "relational", "ACID", "schema", "horizontal scaling", "document"] },
  { title: "Explain JWT authentication and how it works.", description: "What is JSON Web Token (JWT), what are its components, and how is it used for authentication?", role: "Backend", topic: "Security", difficulty: "Medium", modelAnswer: "JWT is a compact token with three parts: Header (algorithm), Payload (claims), Signature (created by signing with secret key). The server generates a JWT on login; client sends it in the Authorization header with subsequent requests.", explanation: "JWT's statelessness makes it scalable but token revocation is complex.", keywords: ["JWT", "header", "payload", "signature", "Bearer token", "stateless", "expiry"] },
  { title: "What is middleware in the context of Express.js?", description: "Define middleware, explain how it works in Express.js, and give examples.", role: "Backend", topic: "Node.js", difficulty: "Easy", modelAnswer: "Middleware in Express.js are functions with access to request, response, and next middleware function. They can execute code, modify req/res, end the request-response cycle, or call next().", explanation: "Middleware is the fundamental building block of Express applications.", keywords: ["middleware", "Express", "req", "res", "next", "request-response cycle", "authentication"] },
  { title: "Explain ACID properties in database transactions.", description: "What do Atomicity, Consistency, Isolation, and Durability mean?", role: "Backend", topic: "Databases", difficulty: "Medium", modelAnswer: "ACID: Atomicity (all-or-nothing), Consistency (valid state to valid state), Isolation (concurrent transactions appear sequential), Durability (committed data persists even after crashes).", explanation: "ACID properties are fundamental to financial and critical data systems.", keywords: ["ACID", "atomicity", "consistency", "isolation", "durability", "transaction", "rollback"] },
  { title: "What is caching and what are common caching strategies?", description: "Explain caching in backend systems and common strategies.", role: "Backend", topic: "System Design", difficulty: "Medium", modelAnswer: "Caching stores frequently accessed data in fast storage to reduce latency. Common strategies: Cache-Aside, Write-Through, Write-Behind, Read-Through. Redis is the most popular caching layer.", explanation: "Caching is a critical scalability tool but introduces complexity.", keywords: ["caching", "Redis", "cache-aside", "write-through", "TTL", "cache invalidation"] },
  { title: "Explain the N+1 query problem and how to solve it.", description: "What is the N+1 query problem in ORMs and what are the solutions?", role: "Backend", topic: "Databases", difficulty: "Hard", modelAnswer: "The N+1 problem occurs when fetching N records then executing one additional query per record. Solutions: eager loading/JOINs, DataLoader/batching, denormalization.", explanation: "The N+1 problem is one of the most common performance issues in applications using ORMs.", keywords: ["N+1", "query", "ORM", "eager loading", "JOIN", "DataLoader", "batching"] },
  { title: "What is horizontal vs vertical scaling?", description: "Explain the difference between horizontal and vertical scaling with trade-offs.", role: "Backend", topic: "System Design", difficulty: "Medium", modelAnswer: "Vertical scaling adds more resources to a single server. Horizontal scaling adds more server instances and distributes load with a load balancer. Modern cloud architectures prefer horizontal scaling for stateless services.", explanation: "Horizontal scaling is the foundation of cloud-native architecture.", keywords: ["horizontal scaling", "vertical scaling", "load balancer", "stateless", "high availability"] },
  { title: "What are microservices and how do they compare to a monolith?", description: "Explain the microservices architecture pattern and its trade-offs.", role: "Backend", topic: "System Design", difficulty: "Hard", modelAnswer: "A monolith is a single deployable unit. Microservices decompose into small, independently deployable services communicating over APIs. Benefits: independent deployment, fault isolation. Drawbacks: distributed system complexity, operational overhead.", explanation: "Microservices are not inherently better — they trade simplicity for scalability.", keywords: ["microservices", "monolith", "API gateway", "service discovery", "independent deployment"] },

  // ── FULL-STACK ────────────────────────────────────────────
  { title: "What is the difference between SSR, SSG, and CSR?", description: "Compare Server-Side Rendering, Static Site Generation, and Client-Side Rendering.", role: "Full-Stack", topic: "Web Architecture", difficulty: "Medium", modelAnswer: "CSR: server sends minimal HTML shell, JS renders in browser. SSR: server renders full HTML on every request. SSG: pages pre-rendered at build time. Next.js supports all three.", explanation: "Choosing the rendering strategy impacts performance, SEO, infrastructure cost.", keywords: ["SSR", "SSG", "CSR", "hydration", "First Contentful Paint", "SEO", "TTFB", "CDN"] },
  { title: "Explain the HTTP request-response lifecycle.", description: "Walk through what happens from URL entry to page fully loaded.", role: "Full-Stack", topic: "Web Architecture", difficulty: "Medium", modelAnswer: "1. DNS resolution. 2. TCP connection. 3. TLS handshake. 4. HTTP GET request. 5. Server processes, queries DB. 6. HTTP response. 7. Browser parses HTML, builds DOM. 8. Fetches CSS/JS. 9. CSSOM built, Render Tree. 10. Layout, Paint, Composite.", explanation: "This tests understanding of networking, HTTP, browser rendering, and server-side processing.", keywords: ["DNS", "TCP", "TLS", "HTTP", "GET", "response", "DOM", "CSSOM", "render tree"] },
  { title: "How do you handle authentication in a full-stack application?", description: "Describe a complete authentication flow including token management and security considerations.", role: "Full-Stack", topic: "Security", difficulty: "Hard", modelAnswer: "1. User submits credentials over HTTPS. 2. Server verifies against hashed password (bcrypt). 3. Server generates JWT access token (15min) and refresh token (7days, httpOnly cookie). 4. Access token in memory on client. 5. API requests send access token in Authorization header.", explanation: "Authentication security is multi-layered. The access+refresh token pattern gives best security and UX.", keywords: ["JWT", "refresh token", "access token", "httpOnly", "bcrypt", "HTTPS", "CSRF", "XSS"] },
  { title: "What is GraphQL and how does it differ from REST?", description: "Explain GraphQL and key differences from REST APIs.", role: "Full-Stack", topic: "APIs", difficulty: "Medium", modelAnswer: "GraphQL is a query language where clients specify exactly what data they need. Differences from REST: single endpoint, client-specified queries, no over/under-fetching, strongly typed schema.", explanation: "GraphQL shines in complex domain models with many interconnected entities.", keywords: ["GraphQL", "REST", "query", "mutation", "subscription", "schema", "resolver", "over-fetching"] },
  { title: "Explain CORS and how to configure it properly.", description: "What is Cross-Origin Resource Sharing and how do you configure it?", role: "Full-Stack", topic: "Security", difficulty: "Medium", modelAnswer: "CORS is a browser security mechanism restricting cross-origin requests. Configure via: Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers, Access-Control-Allow-Credentials.", explanation: "CORS is a browser enforcement — it doesn't affect server-to-server requests.", keywords: ["CORS", "Same-Origin Policy", "preflight", "OPTIONS", "Access-Control-Allow-Origin"] },

  // ── SDE-1 ─────────────────────────────────────────────────
  { title: "Explain the time and space complexity of common sorting algorithms.", description: "Compare Bubble Sort, Merge Sort, Quick Sort, and Heap Sort.", role: "SDE-1", topic: "Algorithms", difficulty: "Medium", modelAnswer: "Bubble Sort: O(n²) all cases, O(1) space. Merge Sort: O(n log n) all cases, O(n) space, stable. Quick Sort: O(n log n) average, O(n²) worst, O(log n) space. Heap Sort: O(n log n) all cases, O(1) space.", explanation: "No single algorithm wins in all dimensions — trade-offs determine the best choice.", keywords: ["Bubble Sort", "Merge Sort", "Quick Sort", "Heap Sort", "O(n²)", "O(n log n)", "stable"] },
  { title: "What is a hash table and how does it handle collisions?", description: "Explain how hash tables work internally including collision resolution.", role: "SDE-1", topic: "Data Structures", difficulty: "Medium", modelAnswer: "A hash table provides O(1) average-case lookup. A hash function converts a key into an array index. Collision resolution: Chaining (linked list per bucket) or Open Addressing (probe for next empty slot).", explanation: "Hash tables are arguably the most important data structure in software engineering.", keywords: ["hash table", "hash function", "collision", "chaining", "open addressing", "load factor"] },
  { title: "Explain binary search and implement it.", description: "Describe binary search, its prerequisites, time complexity, and common pitfalls.", role: "SDE-1", topic: "Algorithms", difficulty: "Easy", modelAnswer: "Binary search finds a target in a sorted array in O(log n) time by repeatedly halving the search space. Requires sorted array. Common pitfalls: integer overflow with mid calculation, off-by-one errors.", explanation: "Binary search is fundamental and appears in many forms.", keywords: ["binary search", "sorted array", "O(log n)", "left", "right", "mid", "halving"] },
  { title: "What is dynamic programming? Explain with an example.", description: "Define dynamic programming and describe the top-down and bottom-up approaches.", role: "SDE-1", topic: "Algorithms", difficulty: "Hard", modelAnswer: "Dynamic programming solves problems by breaking them into overlapping subproblems, solving each once, and storing results. Top-down: recursive + cache (memoization). Bottom-up: iterative table filling (tabulation).", explanation: "DP is one of the hardest concepts in CS interviews. Start by writing the recursive solution, then add memoization.", keywords: ["dynamic programming", "memoization", "tabulation", "overlapping subproblems", "optimal substructure"] },
  { title: "Explain the differences between a stack and a queue.", description: "Compare stacks and queues, their operations, time complexities, and real-world use cases.", role: "SDE-1", topic: "Data Structures", difficulty: "Easy", modelAnswer: "Stack is LIFO (Last In, First Out): push, pop, peek — all O(1). Used for function call stack, undo/redo, DFS. Queue is FIFO (First In, First Out): enqueue, dequeue — O(1). Used for task scheduling, BFS.", explanation: "Stacks and queues are fundamental building blocks of many algorithms.", keywords: ["stack", "queue", "LIFO", "FIFO", "push", "pop", "enqueue", "dequeue", "DFS", "BFS"] },
  { title: "What are the types of tree traversals?", description: "Describe in-order, pre-order, post-order, and level-order tree traversals.", role: "SDE-1", topic: "Data Structures", difficulty: "Medium", modelAnswer: "In-order (Left-Root-Right): gives sorted output for BSTs. Pre-order (Root-Left-Right): serialize a tree. Post-order (Left-Right-Root): delete a tree. Level-order (BFS): visits level by level using a queue.", explanation: "Tree traversal is fundamental to tree and graph algorithms.", keywords: ["in-order", "pre-order", "post-order", "level-order", "BFS", "DFS", "BST", "recursive"] },
  { title: "Explain object-oriented programming principles (SOLID).", description: "Describe the five SOLID principles with examples.", role: "SDE-1", topic: "OOP", difficulty: "Medium", modelAnswer: "SOLID: Single Responsibility (one reason to change), Open/Closed (open for extension, closed for modification), Liskov Substitution (subclasses substitutable for parent), Interface Segregation (small specific interfaces), Dependency Inversion (depend on abstractions).", explanation: "SOLID principles are the foundation of maintainable OOP code.", keywords: ["SOLID", "Single Responsibility", "Open/Closed", "Liskov", "Interface Segregation", "Dependency Inversion"] },
  { title: "What is the difference between a process and a thread?", description: "Explain processes and threads, how they relate, and common concurrency challenges.", role: "SDE-1", topic: "Operating Systems", difficulty: "Medium", modelAnswer: "A process is an independent program with its own memory space. A thread is a lightweight unit within a process that shares the process's memory. Concurrency challenges: race conditions, deadlocks, livelocks, starvation.", explanation: "Process vs thread is fundamental to OS and systems programming.", keywords: ["process", "thread", "memory space", "shared memory", "race condition", "deadlock", "concurrency"] },

  // ── QA ────────────────────────────────────────────────────
  { title: "What is the difference between verification and validation in software testing?", description: "Explain verification and validation, how they differ, and when each is applied.", role: "QA", topic: "Testing Fundamentals", difficulty: "Easy", modelAnswer: "Verification: checking that software is built correctly — 'are we building the product right?' (against specs). Validation: checking that the right product is built — 'are we building the right product?' (against user needs).", explanation: "Verification = 'did we build it right?', Validation = 'did we build the right thing?'", keywords: ["verification", "validation", "specification", "user needs", "static analysis", "UAT", "dynamic testing"] },
  { title: "Explain the testing pyramid and testing types.", description: "Describe the testing pyramid model and different types of tests.", role: "QA", topic: "Testing Strategy", difficulty: "Easy", modelAnswer: "The testing pyramid: many unit tests at base, fewer integration tests in middle, even fewer E2E tests at top. Unit tests: fast, cheap, precise. Integration tests: catch integration issues. E2E tests: simulate real user journeys, slowest, most expensive.", explanation: "The testing pyramid guides test investment for faster feedback loops.", keywords: ["testing pyramid", "unit test", "integration test", "E2E", "end-to-end", "fast", "brittle"] },
  { title: "What is the difference between black-box and white-box testing?", description: "Compare black-box and white-box testing approaches.", role: "QA", topic: "Testing Fundamentals", difficulty: "Easy", modelAnswer: "Black-box testing: no knowledge of internal implementation, tests based on requirements. Techniques: equivalence partitioning, boundary value analysis. White-box testing: full knowledge of internal code, covers specific code paths.", explanation: "Both approaches are complementary — black-box ensures user expectations, white-box ensures code paths.", keywords: ["black-box", "white-box", "equivalence partitioning", "boundary value", "code coverage", "branch coverage"] },
  { title: "How do you write effective test cases?", description: "Describe the anatomy of a good test case and best practices.", role: "QA", topic: "Test Design", difficulty: "Medium", modelAnswer: "A good test case has: ID, description, preconditions, test steps, test data, expected result, actual result, pass/fail status. Best practices: one assertion per test, tests should be independent and repeatable, cover happy path, sad path, and edge cases.", explanation: "Well-written test cases are documentation describing how the system should behave.", keywords: ["test case", "precondition", "test steps", "expected result", "assertion", "independent", "repeatable"] },
  { title: "What is API testing and how do you approach it?", description: "Describe what API testing covers, types of tests, tools used, and best practices.", role: "QA", topic: "API Testing", difficulty: "Medium", modelAnswer: "API testing validates APIs without a UI. Covers: functional testing, negative testing, authentication testing, performance testing, security testing. Tools: Postman, REST Assured, Supertest, k6.", explanation: "API testing is faster and more stable than E2E browser tests.", keywords: ["API testing", "Postman", "REST", "status codes", "negative testing", "authentication", "performance"] },
  { title: "What is regression testing and when is it performed?", description: "Explain regression testing, its purpose, and when to run it.", role: "QA", topic: "Testing Strategy", difficulty: "Easy", modelAnswer: "Regression testing verifies new code changes haven't broken existing functionality. Performed after: bug fixes, new features, refactoring, before releases. Automated regression suites in CI/CD provide continuous testing.", explanation: "Regression testing is the safety net for continuous delivery.", keywords: ["regression testing", "CI/CD", "automation", "risk-based", "existing functionality", "bug fix"] },
  { title: "Explain Selenium WebDriver and how it automates browsers.", description: "Describe how Selenium WebDriver works, its architecture, and best practices.", role: "QA", topic: "Test Automation", difficulty: "Medium", modelAnswer: "Selenium WebDriver controls browsers programmatically via WebDriver API → WebDriver protocol → browser driver → browser. Best practices: prefer IDs, use explicit waits, implement Page Object Model pattern.", explanation: "Understanding Selenium fundamentals applies to all browser automation.", keywords: ["Selenium", "WebDriver", "ChromeDriver", "locator", "XPath", "CSS selector", "Page Object Model"] },
  { title: "What is a bug life cycle?", description: "Describe the stages a defect goes through from discovery to closure.", role: "QA", topic: "Testing Fundamentals", difficulty: "Easy", modelAnswer: "Bug Life Cycle: New → Assigned → Open → Fixed → Retesting → Verified → Closed. Additional states: Reopened, Rejected, Deferred, Duplicate. Severity (impact) vs Priority (order of fixing).", explanation: "The distinction between severity and priority is frequently misunderstood.", keywords: ["bug life cycle", "defect", "severity", "priority", "reproduce", "retesting", "closed", "reopened"] },
  { title: "Explain performance testing and its types.", description: "Describe performance testing, the different types, and tools used.", role: "QA", topic: "Performance Testing", difficulty: "Medium", modelAnswer: "Performance testing types: Load Testing (normal load baseline), Stress Testing (beyond capacity), Spike Testing (sudden extreme load), Soak Testing (sustained load over time). Tools: JMeter, k6, Gatling, Locust.", explanation: "Establishing performance baselines early helps detect regressions before they impact users.", keywords: ["performance testing", "load testing", "stress testing", "spike testing", "soak testing", "JMeter", "k6"] },
  { title: "What is test-driven development (TDD)?", description: "Explain TDD, its Red-Green-Refactor cycle, benefits, and challenges.", role: "QA", topic: "Test Design", difficulty: "Medium", modelAnswer: "TDD cycle: Red (write failing test), Green (write minimum code to pass), Refactor (clean up while keeping tests green). Benefits: forces modular design, provides test suite, living documentation. Challenges: initial slowdown, not suitable for UI testing.", explanation: "TDD fundamentally changes how you think about code — design interface before implementation.", keywords: ["TDD", "test-driven development", "red-green-refactor", "failing test", "refactor", "living documentation"] },
];

// ── Seed users ─────────────────────────────────────────────
const USERS = [
  {
    name: "Alex Chen",
    email: "alex@example.com",
    passwordHash: "password123",
    avatar: "AC",
    role: "Frontend",
    isAdmin: false,
  },
  {
    name: "Admin User",
    email: "admin@prepify.dev",
    passwordHash: "admin123",
    avatar: "AU",
    role: "Full-Stack",
    isAdmin: true,
  },
];

// ── Main seed function ──────────────────────────────────────
const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected");

    // Clear existing data
    await Question.deleteMany({});
    await User.deleteMany({});
    console.log("🗑️  Cleared existing questions and users");

    // Insert all questions
    await Question.insertMany(QUESTIONS);
    console.log(`✅ Seeded ${QUESTIONS.length} questions`);

    // Insert users (passwords will be hashed by pre-save hook)
    for (const userData of USERS) {
      await User.create(userData);
    }
    console.log(`✅ Seeded ${USERS.length} users`);
    console.log("   → User:  alex@example.com / password123");
    console.log("   → Admin: admin@prepify.dev / admin123");

    console.log("\n🎉 Database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error.message);
    process.exit(1);
  }
};

seed();
